apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testdeployments.test.example.com
spec:
  group: test.example.com
  names:
    kind: TestDeployment
    plural: testdeployments
    singular: testdeployment
    shortNames:
      - td
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                replicas:
                  type: integer
